name: github-actions
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check . 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/upload-artifact@v3
        with:
          python-version: '3.10.6'
      - name: "numpy Install"
        run: pip install numpy
      - name: "matplotlib Install"
        run: pip install matplotlib
      - name: "pytest Install"
        run: pip install pytest
      - name: "Coverage Install"
        run: pip install coverage
      - name: "Run Test"
        run: coverage run -m pytest
      - name: "Generate Coverage Report"
        run:  coverage report -m > Report.Coverage